version: '2'
services:

  postgres:
      image: postgres:9.6.2
      ports:
          - 5432:5432
      environment:
        POSTGRES_DB: traindelays
  redis:
    image: redis:3.2-alpine
    command: ["redis-server"]
    hostname: redis
    ports:
          - 6379:6379
  influxdb:
    image: influxdb:1.3.9
    ports:
          - 8086:8086
    environment:
        INFLUXDB_DB: traindelays