ALTER TABLE subscribers
ADD COLUMN email_verified BOOLEAN NULL;

ALTER TABLE subscribers
ADD COLUMN name VARCHAR(100) NULL;

ALTER TABLE subscribers
ADD COLUMN first_name VARCHAR(100) NULL;

ALTER TABLE subscribers
ADD COLUMN family_name VARCHAR(100) NULL;

ALTER TABLE subscribers
ADD COLUMN locale VARCHAR(10) NULL;