CREATE TABLE IF NOT EXISTS schedule_secondary (
  id SERIAL PRIMARY KEY,
  schedule_train_id     VARCHAR(10)    NOT NULL,
  service_code    VARCHAR(10)   NOT NULL,
  atoc_code VARCHAR(10) NOT NULL,
  stop_sequence SMALLINT NOT NULL,
  stanox_code VARCHAR(10) NOT NULL,
  subsequent_stanox_codes VARCHAR(50)[] NOT NULL,
  subsequent_arrival_times VARCHAR(50)[] NOT NULL,
  monday   BOOLEAN NOT NULL,
  tuesday   BOOLEAN NOT NULL,
  wednesday   BOOLEAN NOT NULL,
  thursday   BOOLEAN NOT NULL,
  friday   BOOLEAN NOT NULL,
  saturday   BOOLEAN NOT NULL,
  sunday   BOOLEAN NOT NULL,
  schedule_start DATE NOT NULL,
  schedule_end DATE NOT NULL,
  location_type VARCHAR(5) NOT NULL,
  arrival_time TIME NULL,
  departure_time TIME NULL,
  days_run_pattern VARCHAR(10) NOT NULL,
  stp_indicator VARCHAR(10) NOT NULL,
  train_category VARCHAR(10) NULL,
  train_status VARCHAR(10) NULL,
  association_id INTEGER NOT NULL,
  CONSTRAINT schedule_secondary_unique_cons UNIQUE(association_id, stop_sequence)
);
